spring:  
  profiles:
    active: dev

logging:
  level:
    com.backend.challenge: DEBUG


management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
   
---
spring:
    profiles: dev
    h2:
      console:
        enabled: true
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:reservation
      username: sa
      password: 
    jpa:
      show_sql: true
      hibernate:
        ddl-auto: none
